network:
  name: "localnet"
  mode: "api" # If you want the framework to use your local node running in a specific network, set this to "local"
  gas:
    cost: 0.01 # Estimated gas cost that will be used for funding calculations etc.
    limit: 53000 # Higher limit than regular txs (21000) - seems there are some issues occasionally when using a lower gas limit 
    price: 1

application:
  infinite: false
  count: 100
  pool_size: 10
  verbose: true
  passphrase: ""

funding:
  confirmation_wait_time: 16 # This will be multiplied * 4 to deal with the general slowness of the staking network
  attempts: 5
  gas:
    cost: 0.0001
    limit: 53000
    price: 1
